name: Build iOS

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install .NET iOS Workload
      run: dotnet workload install ios

    - name: Publish iOS App
      run: |
        dotnet publish -f net8.0-ios -c Release -p:BuildIpa=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="-" -p:CodesignProvision="-"

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: BlackIOS.ipa
        path: bin/Release/net8.0-ios/ios-arm64/publish/*.ipa
